# The plugin detects that a player is using a mod using translation
#  keys via minecraft exploit using packetevents.
#
# It works at the packet level as follows:
# - Upon connection, a block update packet is sent to the sign.
# - A sign update packet is sent to the mod's translation key.
# - A sign opening packet is sent.
# - A sign closing packet is sent.
#
# If the player responds with a packet that doesn't have the
#  default value in place of the translation text,
#  it means the player is using that mod.

# Color codes supported:
# - MiniMessage (<n> | <#rrggbb>)
# - Modern Ampersand (&n | &#rrggbb)
# - Legacy Ampersand (&n | &x&r&r&g&g&b&b)
action:
  # Available types:
  # - Message - sends message to player in chat
  # - Command - sends a command from the console
  # - Kick - kicks a player with a reason
  type: message
  content:
    - "&cYou are using a cheat mod that is not allowed on [Your Server] (%mod%!),"
    - "&cIf you join the game with this you will be banned!"

default: "fallb"
timeout-kick: "&fTimed out"
disallowed-mods:
  "Meteor": "key.meteor-client.open-gui"
  "Item Scroller": "itemscroller.gui.button.config_gui.generic"
  "Freecam": "key.freecam.toggle"
  "Accurate Block Placement": "text.autoconfig.accurateblockplacement.title"

# Logging packets & results
debug: false